// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btfhfujdrvvkdiobitsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0ZmhmdWpkcnZ2a2Rpb2JpdHNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NjgyMjEsImV4cCI6MjA2MzI0NDIyMX0.JOhs0_xqMXYBNOdakbtiwHhBBYhMjKB4CtAOkvfuI9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);